name: Calculate Test Coverage

on:
  push:
    branches: [main]
    paths:
      - "**.py"

jobs:
  coverage:
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip
    - name: Install Python libraries
      run: pip install --upgrade -r .github/workflows/requirements/requirements.txt
    - name: "Run coverage"
      run: |
        (pytest --co && coverage run -m pytest) || echo "Nothing to test"
        coverage report -m --format=markdown > COVERAGE.md
        coverage-badge -fo coverage.svg
    - name: Commit changes
      with:
        COMMIT_MESSAGE: "Update coverage"
      uses: stefanzweifel/git-auto-commit-action@v4
