name: Lint, Format and Security Check Pull Request

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  lint-format-security-check:
    name: Lint, Format and Security Check
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      ALTERED_PYTHON_FILES: $(git diff --name-only main..HEAD | grep -P '^.*\.py$' | tr '\n' ' ')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip

    - name: Install Python libraries
      run: pip install --upgrade -r .github/workflows/requirements/requirements.txt

    - name: Format with ruff and black
      run: |
        ruff --fix --ignore E501 $ALTERED_PYTHON_FILES
        black $ALTERED_PYTHON_FILES

    - name: Commit formatting changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply auto format"

    - name: Lint with mypy
      run: |
        mypy $ALTERED_PYTHON_FILES

    - name: Security check with bandit
      run: |
        bandit $ALTERED_PYTHON_FILES
